config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registration: 'users/registrations'}
  
  resources :users do
    resource :profile
  end
  
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
  
    if @contact.save
      name = params[:contact][:name]      #for email delivery
      email = params[:contact][:email]    #for email delivery
      body = params[:contact][:comments]  #for email delivery

      ContactMailer.contact_email(name, email, body).deliver #method from contact_email, parameters from the above variables

      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      flash[:danger] = "Error occured, message has not been sent."
      redirect_to new_contact_path
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end

  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user! #only members can edit
  before_action :only_current_user  #can only edit current user's profile

  def new # form where a user can fill out their own profile
    @user = User.find(params[:user_id])
    @profile = Profile.new
  end

  def create
    @user = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path(params[:user_id])
    else
      render action: :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user = User.find( params[:user_id] )
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
        render action: :edit
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end

    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end


end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :select_plan, only: :new

  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end

  #before filter isn't working, so this isn't being activated.
  private
    def select_plan
      unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
        flash[:notice] = "Please select a membership plan to sign up."
        redirect_to root_url
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    # @users = User.includes(:profile)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end 
  end
  
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-center">Contact Us</h1>
    <p class="text-center">Reach out if you have any questions or comments.</p>
    <div class="well">
      <%= form_for @contact do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :name, class: 'form-control' %>
        </div>

        <%= f.submit 'Submit', class: 'btn btn-default' %>

      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev Match</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-users"></i>
        Dev Match
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <%# else %>
          <%#= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Community", users_path %></li>
          <li><%= link_to "My Account", edit_user_registration_path %></li>
        <% end %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
  
<!-- <div class="container"> -->
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  
  <%= yield %>
<!-- </div> -->
  
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
<h2>About Us</h2>
<p>Welcome to Dev Match. We are a community of developers, entrepreneurs, and investors who are interested in meeting one another and sharing ideas.</p>
</div>

app/views/pages/home.html.erb
<div class="container-fluid poopy" id="landing" style="min-height: 628px;">
  
  <div class="container">
    <div class="row">
      <div class="col-sm-8">

        <h1>Welcome to North Math!</h1>
        <h3><i>Tutoring in the Digital Age</i></h3>

        <p class="lead">Professional digital tutoring and education services. From kindergarden to high school, we tutor students of all ages and develop their math skills so that they will thrive in a world increasingly driven by data and technology.</p>

        <p class="lead">Sign up today, and receive one hour of free math tutoring!</p>

      </div>
        
      <div class="col-sm-4">
        <div class="login_container">      
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field form-group">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, class: 'form-control' %>
            </div>

            <div class="field form-group">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
            </div>
         
            <div class="actions form-group">
              <%= f.submit "Log in", class: 'btn btn-success' %>
            </div>

            <% if devise_mapping.rememberable? -%>
              <div class="field form-group ">
                <%= f.check_box :remember_me %>
                <%= f.label :remember_me %>
              </div>
            <% end -%>
        
            <%= render "devise/shared/links" %>

          <% end %>
        </div> 
        
        <div class="register_container">
          <div class="row">
            <p class="lead signupText">New to North Math?<span class="notBold"> Sign up</span></p>
          </div>
        
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {id: 'basic_form'}) do |f| %>
  <%= devise_error_messages! %>

  <%= hidden_field_tag 'plan', params[:plan] %>

  <div class="field form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'%>
  </div>

  <div class="actions form-group">
    <%= f.submit "Sign up", class: 'btn btn-warning' %>
  </div>

<% end %>

        </div>





      </div>
    


    </div>
  </div>
  
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Profile</h1>
    <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="text-center">Dev Match Community</h1>
    <p>Welcome to the Dev Match community. Users must fill out a profile in order to be visible in the community.</p>
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %> <!-- only show if the users made a profile -->
        <li>
          <div class="well row <%= cycle('white-bg', '') %>">
            <div class="col-sm-4 text-center"> <!--alternates between the blank place -->
              <% if user.profile.avatar %>
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb, :class => "avatar"), class: 'user-index-avatar' %> <!-- thumb is from the profile.rb paperclip model-->
                <% end %>
              <% end %>
            </div>
            
            <div>
              <%= link_to user do %>
                <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
              <% end %>
              <p>
                <%= user.profile.job_title %> 
                <% if user.plan_id == 2 %>
                  <span class="label label-danger">Premium</span>
                <% else %>
                  <span class="label label-primary">Basic</span>
                <% end %>
              </p>
            </div>
          </div>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %>
  </div>
  <div class="col-md-6">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><span class="job-title-icon"><%= job_title_icon %></span> <%= @user.profile.job_title %></h3>
    <div class="well profile-block profile-description">
      <h3>Description</h3>
      <%= @user.profile.description %>
    </div>
    
    <% if true#current_user.plan_id == 2 %>
      <div class="well profile-block contact-info">
        <h3>Contact Info</h3>
        <%= @user.profile.phone_number %><br/>
        <%= @user.profile.contact_email %><br/>
      </div>
    <% end %>
    
  </div>
</div>